server:  
  port: ${PORT:8761}
    
eureka:  
  instance:
    hostname: 128.199.228.211
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false  