def CONTAINER_NAME="gateway-service"
def CONTAINER_TAG="latest"
def DOCKER_HUB_USER="boriphuth"
def HTTP_PORT="8765"

node(label:'builder') {

        stage('Initialize') {
        def dockerHome = tool 'Docker'
        def mavenHome  = tool 'Maven'
        env.PATH = "${dockerHome}/bin:${mavenHome}/bin:${env.PATH}"
        }

        stage('Checkout') {
            git url: 'https://github.com/boriphuth/sample-spring-microservices.git', credentialsId: 'github-id', branch: 'master'
        }

        stage('Build') {
            sh 'mvn clean install'

            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }

        stage('Image') {
            dir ('gateway-service') {
                docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
                def app = docker.build("${DOCKER_HUB_USER}/${CONTAINER_NAME}:${env.version}", '.').push()
                // def app = docker.build("localhost:5000/gateway-service:${env.version}", '.').push()
                }
            }
        }

        stage ('Run') {
            sh "docker pull ${DOCKER_HUB_USER}/${CONTAINER_NAME}:${env.version}"
            sh "docker run -d --rm -p ${HTTP_PORT}:${HTTP_PORT} --name ${CONTAINER_NAME} ${DOCKER_HUB_USER}/${CONTAINER_NAME}:${env.version}"
            // docker.image("${DOCKER_HUB_USER}/${CONTAINER_NAME}:${env.version}").run('-p 8765:8765 -h gateway --name gateway --link discovery --link account --link customer')
            echo "${DOCKER_HUB_USER}/${CONTAINER_NAME}:${env.version} port : ${HTTP_PORT}"
        }
}